### ISSUE TITLE
[BUG] Specifying `variable_names`

### ISSUE THREAD

**Issue by marknovak** [MilesCranmer/PySR#121]
Specifying variable names (e.g., `variable_names = ['N','P']` when `X` has two columns) leads to subsequent problems.  Although the HoF is produced and exported with the appropriate substitutions of `x0` and `x1`, running `model.predict`, for example, 
```
X = 2 * np.random.randn(100, 2)
y = 2 * np.cos(X[:, 1]) + X[:, 0] ** 2 - 2

model = PySRRegressor(variable_names = ['N','P'])
model.fit(X, y)
model.predict
```
results in

> bound method PySRRegressor.predict of PySRRegressor.equations = None

and `model.equations` returns nothing.

In contrast, 
```
model = PySRRegressor()
model.fit(X, y)
model.predict
```
returns results as expected.

- macOS
- PySR 0.7.9

**Comment by MilesCranmer** [comment]
Thanks for raising this @marknovak! I looked into this and it is not an issue for general variable names; this is actually very subtle edge case which happens when you call one variable `N`. It is great you found it because I am sure `N` would be a common variable name, I had simply never tested it.

In general, `variable_names` work fine and are unit-tested. For example, if you specify `variable_names=["N1", "P"]`, your code will work fine as is.

The issue is specifically due to calling one of the variables `N`. Apparently, this is due to the presence of a function with the same name `N` within SymPy (i.e., `from sympy import N`). I never import such a function from SymPy explicitly, but it seems like SymPy's own `lambdify` function, which turns the equation into a function, has internally imported this function!

Will look into solving this. For now I might just add an error when the user specifies a variable name as `N` to be more clear about why this won't work. What do you think?

Cheers,
Miles

**Comment by marknovak** [comment]
Wow.  That would have taken me _forever_ to figure out (had I even tried).  Nicely done.  (And thanks for the quick reply on this Issue too.)

**Comment by MilesCranmer** [comment]
I have an explicit assertion check for this now against all sympy functions... should make this error easier to solve!
