### ISSUE TITLE
Example for considering discontinuous switches (IF and >, <) operators

### ISSUE THREAD

**Issue by jsimons8** [MilesCranmer/PySR#150]
Hi,

First of all, I love this package, it's wonderful! :-)

I am trying to find an expression that describes my data where a discontinuous switching mechanism is an operator I'd like to include. Does there exist an example somewhere that I can adapt? I tried specifying "IF" and ">" as binary operators  but received errors from the Julia backend. How do I allow for equations that discontinuously switch along the lines of if(x_1 > const,.,.) or if(x_1>=x_2,.,.) ?

Moreover, in the plotting example [https://astroautomata.com/PySR/#/examples](url), I believe there is a call to the `predict` method missing. Should it not be `model.predict(X)` rather than `model(X)`? Otherwise, Python complains that `model` is not callable.

Thank you so much!

**Comment by MilesCranmer** [comment]
Thanks! Good question. 

I've done this in the past and I've used the following:
```python
binary_operators=[..., "conditional(x, y) = (x >= 0) ? y : 0"],
extra_sympy_mappings={
    "conditional": lambda x, y: sympy.Piecewise((0, x < 0), (y, True)),
},
```
since PySR only allows binary/unary operators. This binary operator will be equal to `y` if `x >= 0`, and `0` otherwise. The algorithm could compose this to have more complex conditional logic.

The `conditional(x, y) = (x >= 0) ? y : 0` gives the Julia definition of the operator (used during the search), and `{"cons": lambda x, y: sympy.Piecewise((0, x < 0), (y, True)),}` gives the sympy definition of the operator (used for `.predict` and for display). See https://docs.julialang.org/en/v1/manual/control-flow/#man-conditional-evaluation for explanation of the operator `... ? ... : ...`


---

Regarding plotting, good catch! That should indeed be `model.predict`.

**Comment by MilesCranmer** [comment]
(Let me know if you have any other questions)
