### ISSUE TITLE
[Plot for Iterations/Generations with RMSE ]

### ISSUE THREAD

**Issue by fitriaramlan** [MilesCranmer/PySR#254]
Do you have a feature to show a plot between iterations with RMSE?
We have checked the dir(model), and we couldn't find it. 
If you don't have it, could you probably make that in the next pysr version?

**Comment by MilesCranmer** [comment]
Good idea. I don't have time to add it right now, but if you want to give it a shot, a PR would be welcome! 

It would be easier to add this on the Julia side. Here is where the equations are printed to a file: https://github.com/MilesCranmer/SymbolicRegression.jl/blob/de0e51c89ae1a88cfc5a616a9d101b7a4d331dcb/src/SymbolicRegression.jl#L755-L766

you could probably add some code to append to a file over time, so that you can plot it, either live or at the end of training.

**Comment by MilesCranmer** [comment]
This will be added by https://github.com/MilesCranmer/SymbolicRegression.jl/pull/277. The new issue #581 is set up for tracking it, so let's move there.
