### ISSUE TITLE
Hall of fame files are cluttering up my directories

### ISSUE THREAD

**Issue by patrick-kidger** [MilesCranmer/PySR#30]
Can there be an option to not save the results to disk? Generally saving results to disk is a thing I prefer to be in charge of myself, e.g. using Sacred or similar.

**Comment by MilesCranmer** [comment]
Great question; I should add a temporary file option. Note generally you can set the filename of this csv file to whatever you like with the `equation_file` argument (overwrites by default). Here are some notes on this behaviour:

- I completely de-couple Python and Julia. Their only communication is via writing files to disk. This is because I found that PyJulia made distributed compute difficult to set up (and perhaps impossible for multi-node), so instead I just have Python basically meta-program a SymbolicRegression.jl program and run Julia on it. (also much easier to sort out `PATH` issues this way).
- Because of this, the Python actually requires the hall of fame csv file to read back the best equations from Julia.
- For all temporary files other than the equations file, I write to a temp directory that is deleted at the end of training (can turn this off with `delete_tempfiles=False`). This is made system independent with the `tempfile` module.

However, for the hall of fame file, I use the current directory by default, and append the datetime so there is a new file for each run. But one can manually set the location with eg `equation_file="equations.csv"`. This will overwrite whatever file is there. You could use Sacred on that filename, maybe?

So that's one option. The other option, which I don't have yet, is to make an optional flag to just put the equations file into the same temporary directory so it gets deleted after training.

Thoughts?
Cheers,
Miles

**Comment by patrick-kidger** [comment]
Ah, I see; in particular the Python-Julia interop. (Which sounds like no fun at all, I don't envy you.) I think my preferred option would be for a flag that puts the optional file in the same temporary directory.

**Comment by MilesCranmer** [comment]
Sounds good, will add it!

**Comment by MilesCranmer** [comment]
Okay, pushed to master! Will update PyPI soon. Setting `temp_equation_file=True` will now put the hall of fame file into the temporary directory. It will be deleted by default, or you can choose to keep the temp directory with `delete_tempfiles=False`.

Cheers,
Miles

**Comment by patrick-kidger** [comment]
That was fast! First class support, right there. :D

**Comment by MilesCranmer** [comment]
Thanks! 😄 🚀
