### ISSUE TITLE
Error when selecting some operators

### ISSUE THREAD

**Issue by tedwards2412** [MilesCranmer/PySR#37]
Hi!

I've been trying to use a variety of operators and for some of them I get an error. For example if I run:

```
equations = pysr(X, y, niterations=100,
    binary_operators=["plus", "mult", "div", "sub", "pow"],
    unary_operators=[
      "cos", "sin", "asinh", "gamma"
      ])
```
I get
```
Running on julia -O3 /tmp/tmpsva4rkch/runfile.jl
Couldn't find equation file!
```

If I remove the "gamma" from the operator list then this works fine. I get the same error if I use the operator "acosh". I believe these functions. I'm not sure why this is happening since acosh is just a core Julia function whereas gamma is in SpecialFunctions.jl. I also confirmed that a colleague got the same error on a different system. Any thoughts?

**Comment by MilesCranmer** [comment]
Hi @tedwards2412,

Sorry about these errors, I don't test the special functions right now but I should definitely add some. Indeed it looks like gamma, lgamma, erf, erfc, and beta are not being correctly exported by the backend. Fixing this now.

For why `acosh` does not work, this is a different issue. The backend assumes that all operators are defined over the real line, but `acosh(x)` is not actually defined for `x<1`, so I will need to add a wrapper that will map (-infty, infty) to [1, infty) (similar things are done for sqrt, log, etc. to map to positive numbers). The simplest wrapper would be to pass a function like:
```python
unary_operators=["my_acosh(x)=acosh(abs(x)+1)"]
```
to PySR. But I can set something up like this by default.

By the way, sorry there isn't a more helpful error message here. The backend tests all operators for being defined over the real line before starting the search, so I'm not sure why it's not giving a more helpful error message regarding this... are you running in a jupyter notebook by any chance? If you use `procs=0` (serial computation), it should be easier to debug since the errors will happen on the head worker. 

Cheers,
Miles

**Comment by MilesCranmer** [comment]
Okay I've gotten these working; let me know if you encounter any problems.

These required some modifications, e.g., `gamma` I removed the singularities at 0, -1, -2, etc., and just return 0 close to those points.

`acosh` -> `acosh_abs` = acos(abs(x) + 1)

`atanh` -> `atanh_clip` = atanh(mod(x+1, 2) - 1)

`asinh` is left as is.

These will be available in PySR 0.5.16.

Cheers,
Miles

**Comment by MilesCranmer** [comment]
Updated to pip. Let me know if you have any other problems.

By the way - I took out `asin` and `acos` operators for now. It's unclear to me the best way to implement domain wraps for them, so I think I'll leave this up to the user to implement their own choice of clip/modulus.

Cheers!
Miles

**Comment by tedwards2412** [comment]
Great! Thanks for all the fixes. These all work as expected now. You're right, I was running on a Jupyter notebook. I'll try using procs=0.
