### ISSUE TITLE
How to save PySR results?

### ISSUE THREAD

**Issue by jstan15** [MilesCranmer/PySR#73]
Hi, thank you for providing us with a free symbolic regression library.

Since I am new to this and I haven't fully understood everything yet. I would like to save my all results (after 12 hours of computation) from the output of pysr(). I've tried using pickle, shelve, dill and scipy.io but I can't get them to work. I keep getting different types of errors including this one below:

>AttributeError: module '__main__' has no attribute 'inv'
>AttributeError: Can't get attribute 'inv' on <module '__main__'>
>PicklingError: Can't pickle inv: attribute lookup inv on __main__ failed

Would you please advise me on what I should do to save the results so that I can come back and explore them later?

Thank you. 

For reference this is my script that was based on the examples:
```
# Learn equations
  equation = pysr(
      X,
      y[:,ii],
      binary_operators=["plus", "mult"],
      unary_operators=[
          "cos",
          "sin",  # Pre-defined library of operators (see https://pysr.readthedocs.io/en/latest/docs/operators/)
          "inv(x) = 1/x",
      ],
      loss="loss(x, y) = abs(x - y)",  # Custom loss function
      julia_project="../SymbolicRegression.jl",
  )  # Define your own operator! (Julia syntax)
```

**Comment by MilesCranmer** [comment]
Hi @jstan15,

Sorry you are having trouble saving it. It should save the raw equations automatically to a .csv file in the current directory - do you see those? You can load them back in by calling `pysr.get_hof` with the location of that file.

To save the `equations` object that gets outputted, since you are defining a custom operator `inv(x) = 1/x`, you should add:
```
extra_sympy_mappings={"inv": lambda x: 1/x}
```
as an argument to either `pysr` or `get_hof` when you re-load the saved files. This defines the `inv` function for SymPy so it can correctly map it into sympy (and I think the pickling will work correctly then.

**Comment by MilesCranmer** [comment]
Thanks for following up, cloudpickle looks like a nice tool.

Cheers,
Miles
