### ISSUE TITLE
Better defaults

### ISSUE THREAD

**Issue by patrick-kidger** [MilesCranmer/PySR#99]
The following code trundles along *very* slowly (on my beefy server), making an iteration maybe every 20 seconds or so? Over IIRC 4000 total iterations, that's going to take a long time to complete.

```python
import pysr
import numpy as np
model = pysr.PySRRegressor()
x = np.random.rand(10, 2)
y = np.random.rand(10, 2)
model.fit(x, y)
```

For context these are the default arguments I use in practice, which run pretty quickly (I make no claim that these are very well tuned, just that they are sufficient for what I've been trying):
```
niterations=4
ncyclesperiteration=30
populations=100
npop=20
```

And these are the current PySR defaults:
```
niterations=100
ncyclesperiteration=300
populations=20
npop=1000
```

**Comment by MilesCranmer** [comment]
Good point, I may do this. Originally I made the default settings beefier to make PySR more likely to find the true equation if a user tries it for the first time, but on the other hand, it's much slower!

I would suggest toying with `annealing=True` (very good for short runs; though it might need more ncyclesperiteration to actually do much).

Also, `hofMigration=False`, and `fractionReplaced=0.02` might help produce more diversity. Having `hofMigration` on basically means that 10% of every population is replaced with hall of fame equations (i.e., best equations ever found for each complexity) at the end of one iteration, but its very likely too much when you have short `ncyclesperiteration`.

**Comment by patrick-kidger** [comment]
Alright, sounds good!

I don't think it is compile times. Whilst it's definitely true that that's an issue, I'm only talking here about the time it takes to complete an iteration.

**Comment by MilesCranmer** [comment]
Yeah after thinking about this more, it really makes sense to have the default parameters lighter rather than beefier. It just feels more natural to me to look up how to make some model spend _more_ time, rather than less. I would never think about how to make a model spend less time.

The bonus of a shorter time is users can also quickly tweak parameters and see the effects.

**Comment by patrick-kidger** [comment]
> I would never think about how to make a model spend less time.

We've not been working under the same hardware constraints I see ;)

Anyway, great! :D

**Comment by MilesCranmer** [comment]
Oh what I meant was that if I try an sklearn algorithm out, and it's very very slow, then I may just move on to another algorithm, rather than try to tune it and get it faster.

Whereas if an algorithm is super fast from the start (even if its sub-par performance), then I feel better about trying to increase the steps to get a better result. 

But yeah, I think this will be a good change!
